version: '3.3'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: leetcode
      MYSQL_USER: leetcode
      MYSQL_PASSWORD: secretpassword
      MYSQL_ROOT_PASSWORD: secretpassword
    ports:
      - 13306:3306
    volumes:
      - my-db:/var/lib/mysql
  pg:
    image: postgres
    ports:
    - 15432:5432
    environment:
      POSTGRES_USER: leetcode
      POSTGRES_PASSWORD: secretpassword

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
    - 11433:1433
    environment:
      MSSQL_SA_PASSWORD: Leetcode@123
      ACCEPT_EULA: "Y"

# Names our volume
volumes:
  my-db:
